version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
