name: Deploy to Vercel

on:
  push:
    branches: [develop]
    pull_request: [develop]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci

    - name: Install Vercel CLI
      run: npm install -g vercel
    - name: Deploy to Vercel
      run: |
        vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
        vercel build --token=$VERCEL_TOKEN
        vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}